### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by TheCrawling-Chaos** [minis-patchers/SynWeaponKeywords#15]
It throws an error when the patch is being created, where it worked perfectly before. This is the error line:

`Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`

**Comment by Minizbot2012** [comment]
I need a full log, not just the exception for this.

**Comment by TheCrawling-Chaos** [comment]
...Y'know, that should have occurred to me. I apologize, it had been a long day already at that point. 

Compiling
Extra data folder already exists. Leaving as is: "E:\Mods - SSE\Synthesis\Data\Skyrim Special Edition\SynWeaponKeywords"
("C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Git\brvtvpgt.ibw\Runner\SynPatcher"): "dotnet" "build \"SynPatcher.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "546b26baf641f789d6ac6559b75672c7daeb9714"
Running
(""): "dotnet" "run --project \"C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Git\brvtvpgt.ibw\Runner\SynPatcher\SynPatcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\" --ExtraDataFolder \"E:\Mods - SSE\Synthesis\Data\Skyrim Special Edition\SynWeaponKeywords\" --DefaultDataFolderPath C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Git\brvtvpgt.ibw\Runner\SynPatcher\Data --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Workspace\Synthesis\1 - SynWeaponKeywords\Synthesis.esp\" --PatcherName SynWeaponKeywords --SourcePath \"C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Workspace\Synthesis\1 - SynBundler\Synthesis.esp\""
Mutagen version: 0.38.1
Mutagen sha: 98bc1f54d752946d24054aef8f6c83053c2cacc5
Synthesis version: 0.23.3
Synthesis sha: 177b7e70fba4339f7bed16321712bc5239ac3a77
run-patcher --DataFolderPath "E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "E:\Mods - SSE\Synthesis\Data\Skyrim Special Edition\SynWeaponKeywords" --DefaultDataFolderPath C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Git\brvtvpgt.ibw\Runner\SynPatcher\Data --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath "C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Workspace\Synthesis\1 - SynWeaponKeywords\Synthesis.esp" --PatcherName SynWeaponKeywords --SourcePath "C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Workspace\Synthesis\1 - SynBundler\Synthesis.esp"
Checking runnability
Checking runnability complete
Prepping state.
Language: English
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at WeaponKeywords.Program.ConvertJson(IRunnabilityState state) in C:\Users\Danci\AppData\Local\Temp\Synthesis\vgef4yly.4qr\Git\brvtvpgt.ibw\Runner\SynPatcher\Program.cs:line 92
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 52
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 52
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 65
   at Synthesis.Bethesda.Execution.Running.Runner.RunSomePatchers.Run(IGroupRun groupRun, PatcherPrepBundle[] patchers, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunSomePatchers.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 59
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 54
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Boolean utf8InEmbeddedStrings, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 47
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 200

**Comment by Minizbot2012** [comment]
I'm gonna guess you're a new user, if so I think I figured this out, and is a rather annoying quirk of Newtonsoft.Json and the Synthesis GUI, it had to do with the patcher for DB updates not getting the DBPatchVer, as there was no DB before the patcher ran, and Synthesis GUI is not moving the database from downloaded into its folder on new installs.... I think I should've fixed this with my recent commits to this, please let me know if it doesn't.

**Comment by TheCrawling-Chaos** [comment]
It works now! Thanks!

As an aside though, that wasn't the first time I used Synthesis or your SynWeaponKeywords patch; I only encountered this issue after I ran an update of both the GUI and the patch. That's why it confused the heck out of me, y'know? I had new mods that needed keywords attached to items, so I was baffled when it was suddenly giving me an error. 

Again, thanks for fixing it!

**Comment by Minizbot2012** [comment]
If it's been a long time since you've used it, I've made many changes including adding a database updater... In this particular case newtonsoft.json was reporting an odd value then for a null (int)... And was confusing the heck out of my db updater. Glad to hear it's working.. I guess I can now officially close this.
