### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by goat9988** [minis-patchers/SynWeaponKeywords#23]
Hello,

Having this problem, do you know why and how to fix it please?

Thanks!

Downloading patch https://raw.githubusercontent.com/minis-patchers/SynDelta/main/SynWeaponKeywords/2.json
System.NullReferenceException: Object reference not set to an instance of an object.
   at MZCommonClass.JsonPatch.Extensions.Pointer(JToken token, IEnumerable`1 path) in C:\Users\user\AppData\Local\Temp\Synthesis\pgkpdxox.aib\Git\pjxsowwr.puv\Runner\SynPatcher\Types\MZCommon\JsonPatch.cs:line 18
   at MZCommonClass.JsonPatch.Extensions.Pointer(JToken token, IEnumerable`1 path) in C:\Users\user\AppData\Local\Temp\Synthesis\pgkpdxox.aib\Git\pjxsowwr.puv\Runner\SynPatcher\Types\MZCommon\JsonPatch.cs:line 20
   at MZCommonClass.JsonPatch.Extensions.Pointer(JToken token, IEnumerable`1 path) in C:\Users\user\AppData\Local\Temp\Synthesis\pgkpdxox.aib\Git\pjxsowwr.puv\Runner\SynPatcher\Types\MZCommon\JsonPatch.cs:line 20
   at MZCommonClass.JsonPatch.Extensions.Pointer(JToken token, IEnumerable`1 path) in C:\Users\user\AppData\Local\Temp\Synthesis\pgkpdxox.aib\Git\pjxsowwr.puv\Runner\SynPatcher\Types\MZCommon\JsonPatch.cs:line 20
   at MZCommonClass.JsonPatch.Add.ApplyTo(JToken obj) in C:\Users\user\AppData\Local\Temp\Synthesis\pgkpdxox.aib\Git\pjxsowwr.puv\Runner\SynPatcher\Types\MZCommon\JsonPatch.cs:line 79
   at MZCommonClass.JsonPatch.Extensions.ApplyTo(IList`1 oplist, JToken obj) in C:\Users\user\AppData\Local\Temp\Synthesis\pgkpdxox.aib\Git\pjxsowwr.puv\Runner\SynPatcher\Types\MZCommon\JsonPatch.cs:line 36
   at WeaponKeywords.Program.ConvertJson(IRunnabilityState state) in C:\Users\user\AppData\Local\Temp\Synthesis\pgkpdxox.aib\Git\pjxsowwr.puv\Runner\SynPatcher\Program.cs:line 87
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass20_0.<<AddRunnabilityCheck>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 166
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 187

**Comment by Minizbot2012** [comment]
Is your network stable? can you open the URL at the top of the log without issue?

**Comment by goat9988** [comment]
Yes my network is stable and I get this code in a black page when I open the URL:



[
  {
    "value": {
      "Contains": "Bound Whip Dual",
      "EQType": "LeftHand"
    },
    "path": "/DB/Whip/NameOverrides/0",
    "op": "add"
  },
  {
    "value": {
      "Contains": "Bound Whip",
      "EQType": "EitherHand"
    },
    "path": "/DB/Whip/NameOverrides/1",
    "op": "add"
  },
  {
    "value": 3,
    "path": "/DBVer",
    "op": "replace"
  }
]

**Comment by Minizbot2012** [comment]
Hmm... I just tested the patcher today, and it worked without an issue... All I can ask you to do at this point is to delete the patcher's data and rerun... there's a button for it in synthesis I believe... do not try to open the settings after hitting it though. The error is occurring in an update mechanism that should not be erroring at this point..

**Comment by Minizbot2012** [comment]
Closing - the patch framework has been majorly updated and may still be updated yet
