### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by PinyaGit** [minis-patchers/SynWeaponKeywords#26]
After the update, the data path is duplicated, because of which the patch cannot be applied
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\FlappyEN\StockGame\data\Data\Skyrim Special Edition\SynWeaponKeywords\patch.json'.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at WeaponKeywords.Program.ConvertJson(IRunnabilityState state) in C:\Users\rootr\AppData\Local\Temp\Synthesis\w0e1cfai.rby\Git\5gtktmrs.ukq\Runner\SynPatcher\Program.cs:line 90
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass20_0.<<AddRunnabilityCheck>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 166
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipelin
```

**Comment by Minizbot2012** [comment]
Hmm... IDK what is going on here... it should be in the extra settings data path of synth, not the game's data path...

**Comment by Minizbot2012** [comment]
I believe I fixed this in the latest version.
