### ISSUE TITLE
"Error: Downloading the latest release of JD for DB patching" after last update

### ISSUE THREAD

**Issue by ssebaa** [minis-patchers/SynWeaponKeywords#29]
Hello!
After last update I'm getting error when compiling below, tried removing user data.
```
Downloading the latest release of JD for DB patching
System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WeaponKeywords.Program.ConvertJson(IRunnabilityState state) in C:\Users\sebas\AppData\Local\Temp\Synthesis\jd2bdy1i.vuf\Git\qt2cl2iq.dfv\Runner\SynPatcher\Program.cs:line 76
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass20_0.<<AddRunnabilityCheck>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 166
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass20_0.<AddRunnabilityCheck>b__0(IRunnabilityState c)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass22_0.<CheckRunnability>b__0(AsyncCheckerFunction check) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 189
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 187
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass44_0.<<InternalRun>b__2>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 470
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass44_0.<InternalRun>b__2(CheckRunnability checkRunnability)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 notParsedFunc)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.InternalRun(String[] args, RunPreferences preferences, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 444
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.InternalRun(String[] args, RunPreferences preferences, IFileSystem fileSystem)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass43_0.<Run>b__0() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 389
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 881
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(String[] args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 389
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(String[] args, IFileSystem fileSystem)
   at WeaponKeywords.Program.Main(String[] args) in C:\Users\sebas\AppData\Local\Temp\Synthesis\jd2bdy1i.vuf\Git\qt2cl2iq.dfv\Runner\SynPatcher\Program.cs:line 19
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at WeaponKeywords.Program.Main(String[] args)
   at WeaponKeywords.Program.<Main>(String[] args)
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WeaponKeywords.Program.ConvertJson(IRunnabilityState state) in C:\Users\sebas\AppData\Local\Temp\Synthesis\jd2bdy1i.vuf\Git\qt2cl2iq.dfv\Runner\SynPatcher\Program.cs:line 76
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass20_0.<<AddRunnabilityCheck>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 166
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 187
   ```

**Comment by Minizbot2012** [comment]
Is your network particularly slow? I may have to rummage around again for another solution for DB patching and updating...

I updated the timeout for this from 5 seconds to 20

**Comment by ssebaa** [comment]
Idk what is slow to you but mine is 2,5 MB/s - so probably slow it struggles at 4k streaming a bit (well a lot)
btw i somehow managed to get a different error sometimes(at random)
```
Downloading patch https://raw.githubusercontent.com/minis-patchers/SynDelta/main/SynWeaponKeywords/0.patch from https://raw.githubusercontent.com/minis-patchers/SynDelta/main/SynWeaponKeywords/0.patch
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'jd.exe' with working directory 'E:\Narzedzia do modow\synthesis\Data\Skyrim Special Edition\SynWeaponKeywords'. Nie moĹĽna odnaleĹşÄ‡ okreĹ›lonego pliku.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at WeaponKeywords.Program.ConvertJson(IRunnabilityState state) in C:\Users\sebas\AppData\Local\Temp\Synthesis\jd2bdy1i.vuf\Git\w5msh5kd.hi0\Runner\SynPatcher\Program.cs:line 119
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass20_0.<<AddRunnabilityCheck>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 166
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 187
```

**Comment by ssebaa** [comment]
oh and ```Nie moĹĽna odnaleĹşÄ‡ okreĹ›lonego pliku.``` means it can't find the file, do i have to install something alongside synthesis?

**Comment by ssebaa** [comment]
nvm last update fixed it. Thanks a lot!
